In [1]:
import numpy as np
1e6 == 1000000

True

In [ ]:
%%timeit
quadrati = np.arange(0, 1000000) ** 2

%%timeit
quadrati = []
for i in range(1000000):
    quadrati.append(i ** 2)

## Creare gli array unidimensionali

In [ ]:
arr_di_zeri = np.zeros(10)
arr_di_zeri

In [ ]:
arr_di_zeri.dtype

In [ ]:
arr_zeri_int = np.zeros(10, dtype=np.int8)
arr_zeri_int

In [ ]:
arr_uni = np.ones(10)
print(arr_uni)
arr_cinque = np.ones(10) * 5 # BROADCAST
print(arr_cinque)

In [ ]:
arr_da_lista = np.array([1, 2, 3, 4, 1000])
arr_da_lista

In [2]:
np.random.uniform(3, 5, 10)

array([4.24895992, 3.43807592, 4.7182637 , 3.70396453, 3.726801  ,
       3.19240092, 4.32270132, 3.51804298, 4.03984632, 3.36513021])

In [ ]:
np.random.randint(1, 7, 10)

In [ ]:
alice = np.random.randint(1, 7, 10)
bob = np.random.randint(1, 7, 10)
print("lanci di alice:", alice)
print("lanci  di  bob:", bob)

In [ ]:
np.count_nonzero(alice > bob)

In [ ]:
array_di_interi = np.arange(4, 10)
array_di_interi

In [3]:
quadrati = np.arange(1,11) ** 2
quadrati

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
altezza = np.random.normal(175, 2, 10000)
altezza

In [ ]:
np.mean(altezza)

In [ ]:
np.std(altezza)

## Indicizzazione per booleani
#### Una delle funzioni più potenti di numpy

In [5]:
dadi = np.random.randint(1, 7, 10)
dadi

array([2, 5, 2, 2, 5, 4, 1, 5, 4, 5])

In [6]:
#lanci > 3?
lanci_gt_3 = dadi > 3
lanci_gt_3

array([False,  True, False, False,  True,  True, False,  True,  True,
        True])

In [7]:
dadi[lanci_gt_3] #indicizzo array con array di booleani

array([5, 5, 4, 5, 4, 5])

In [ ]:
nomi = np.array(['alice', 'bob', 'trudy'])
voti = np.array([7, 9, 2])

In [ ]:
#quali alunni sono sufficienti?
nomi[voti >= 6]

In [4]:
alice = np.random.randint(1, 7, 10)
bob   = np.random.randint(1, 7, 10)
print(alice)
print(bob)
alice[alice > bob]

[2 6 3 1 2 5 2 6 1 3]
[3 3 6 2 1 3 4 4 1 6]


array([6, 2, 5, 6])

### Array bidimensionali
Es: 
 - un'immagine in scale di grigi
 - un'immagine RGB a colori è costituita da 3 array 2D
 - un'immagine RGBA a colori è costituita da 4 array 2D
 - dati in forma di tabella

In [3]:
mat_zeri = np.zeros((3, 6), dtype='int64')
mat_zeri.shape

(3, 6)

In [5]:
array_3d = np.random.uniform(0, 1, (3, 3, 2))
array_3d

array([[[0.88910788, 0.05474528],
        [0.00272385, 0.93800777],
        [0.30885813, 0.7156593 ]],

       [[0.87776942, 0.95141058],
        [0.80867358, 0.88966991],
        [0.25749867, 0.91365506]],

       [[0.43670327, 0.99449129],
        [0.48978528, 0.685503  ],
        [0.52843812, 0.29428371]]])

### operazioni matematiche di aggregazione
per esempio:
- somma
- max, min
- media
- dev standard
- somma cumulata

In [9]:
#somma
arr = np.arange(1, 101)
print(arr)
np.sum(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


5050

In [13]:
arr = np.random.uniform(0, 1, 10)
print(arr)
print(f'max: {np.max(arr)}, min: {np.min(arr)}')
print(f'std: {np.std(arr)}')
print(f'somma comulativa {np.cumsum(arr)}')

[0.76503067 0.59664971 0.21204548 0.87466835 0.41392665 0.17610228
 0.65495166 0.47905983 0.35407829 0.15316865]
max: 0.87466834505424, min: 0.15316864966120025
std: 0.2389494105273774
somma comulativa [0.76503067 1.36168038 1.57372586 2.4483942  2.86232086 3.03842313
 3.69337479 4.17243463 4.52651291 4.67968156]


In [17]:
price = 178
variaz = np.array([8, 3, -20, 6])
price + np.cumsum(variaz)

array([186, 189, 169, 175])

### cambiare forma agli array

In [30]:
array_1d = np.arange(1, 13)
array_1d.reshape((3, -1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### esercizio
dato n intero, generare l'array 2d in questo modo:
    [[1, 2, 3, ..., n],
     [1, 2, 3, ... ,n],
     ...,
     ...,
     [1, 2, 3, ... ,n]];
    con n righe

In [40]:
n = 4
arr = np.arange(1, n**2 + 1)
arr2 = (arr % n).reshape(n, -1)
np.roll(arr2, 1) + 1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [41]:
a1d = np.arange(1, 11)
a1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
a1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
np.random.seed(10)
a2d = np.random.uniform(0, 1, (3, 3))
a2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [68]:
a2d[:,1:]

array([[0.02075195, 0.63364823],
       [0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [69]:
a2d[1:,1:] = 0
a2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.        , 0.        ],
       [0.19806286, 0.        , 0.        ]])

dato n intero, creare un array 1d[0, 1. 0, 1, ...] con len = n

In [72]:
n = 20
arr = np.zeros(n, dtype=np.int8)
arr[1::2] = 1
arr

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
      dtype=int8)

dato n creare array 2d di tipo [[0, 1, 0, 1, ...], [0, 1, 0, 1, ...], ...]

In [94]:
n = 10
arr = np.zeros((n, n), dtype=np.int8)
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

dato v=np.array([1, 2, 3, 1, -2, 4, 3, 1, 2]) trovare min e max locali e globali

In [113]:
v = np.array([1, 2, 3, 1, -2, 4, 3, 1, 2])
print('max:', np.max(v))
print('min:', np.min(v))

prec = np.roll(v, -1)
succ = np.roll(v, 1)
maxLoc = v[(v > prec) & (v > succ)]
maxLoc

max: 4
min: -2


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()