In [3]:
import numpy as np

In [93]:
DIM = 1000
eta = np.random.randint(1, 365, (DIM, 25))
eta = np.sort(eta, axis=1)
print(eta)
eta_r = np.roll(eta, -1, axis=1)

res = eta == eta_r
DIM - np.sum(np.count_nonzero(res,axis=1) == 0)

[[  3   3   5 ... 333 350 351]
 [  6   9  29 ... 275 298 360]
 [ 18  19  35 ... 347 356 364]
 ...
 [  5   9   9 ... 314 339 344]
 [  6   7  50 ... 324 330 354]
 [  5   8  14 ... 334 359 363]]


555