In [1]:
import numpy as np

In [4]:
altezze = np.array([183, 177, 174, 183, 178, 161,
                  177, 185, 192, 176, 194, 178,
                  178, 176, 169, 185, 179, 159,
                  179, 173, 168, 180])

np.random.normal(np.mean(altezze), np.std(altezze), len(altezze))

array([183.14378148, 182.98771979, 202.99022992, 178.9277741 ,
       191.97809793, 185.8049732 , 182.72740314, 169.68382365,
       172.07760318, 165.85474691, 183.54867001, 183.7915478 ,
       185.71843493, 177.32500608, 183.92756139, 162.18852603,
       175.77850697, 181.90217721, 170.10078598, 177.25037798,
       169.5773855 , 167.7800596 ])

In [5]:
altezze_itis = np.random.normal(np.mean(altezze), np.std(altezze), 1200)
altezze_itis

array([175.62817901, 171.24180326, 183.8786533 , ..., 178.44665719,
       169.30994559, 172.26025125])

In [7]:
np.count_nonzero(altezze_itis > 200)

3

In [8]:
altezze_itis[altezze_itis > 200]

array([203.40696752, 201.29561418, 200.93691146])